# Generated by Django 5.2.5 on 2025-08-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_company_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_unique_code',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True, unique=True),
        ),
    ]
